name: Notify Duolingo Streak

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # at every 30th minute from 7:30 to 21:30 (no DST = UTC+2)
    - cron: '30 5-19 * 4-10 *'
    # same thing during DST (UTC+1)
    - cron: '30 6-20 * 1-3,11-12 *'
  workflow_dispatch:
    inputs:
      restoreMessageID:
        description: 'Restore message ID'
        required: false
        type: boolean

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      UV_CACHE_DIR: .uv-cache

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore message ID
        uses: actions/cache/restore@v4
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' || inputs.restoreMessageID }}
        with:
          path: online/.duolingo_message_id
          key: message-id-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: message-id-

      - name: Check Duolingo streak and notify
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DUOLINGO_USERNAME: ${{ secrets.DUOLINGO_USERNAME }}
          DUOLINGO_EMAIL: ${{ secrets.DUOLINGO_EMAIL }}
        run: python online/duolingo_notify.py

      - name: Cache message ID
        uses: actions/cache/save@v4
        with:
          path: online/.duolingo_message_id
          key: message-id-${{ github.run_id }}-${{ github.run_attempt }}
